[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
RELOADEDIIMODS = 'D:\SteamLibrary\Reloaded-II\Mods'
DOTNET_CLI_TELEMETRY_OPTOUT = "1"
PYTHONUTF8 = "1"
PYTHONIOENCODING = "utf-8"
